### ISSUE TITLE
Wound Fend Amulet

### ISSUE THREAD

**Issue by sum1won** [sum1won/summod#108]
motherfucker still needs fixing, apparently

**Comment by Lambert-Simnel** [comment]
What's the issue?

**Comment by sum1won** [comment]
Somebody just told me it is still s10.  I haven't yet confirmed.

**Comment by Lambert-Simnel** [comment]
I've seen no problem with it, costs 10 pearls, requires S1.

**Comment by sum1won** [comment]
Oh, I meant to change it to be 5 pearls
