### ISSUE TITLE
Integration with other tools

### ISSUE THREAD

**Issue by sum1won** [sum1won/summod#11]
Moggers, you said something about setting up your server so it can simply grab the most recent version from here.  I'm wondering if it is possible to create a similar tool for the modinspector, which I can just suggest to larzm42 as a pull request.

**Comment by Moggers** [comment]
Rather than making an issue here. You should go to dom4inspector's issues page and create a feature request for it.

> Which I can just suggest to larzm42 as a pull request

If you were to fork the inspector and implement it, then yeah you could open a pull request for it.

**Comment by sum1won** [comment]
Ok, forked.  Now I'm going to (someday) try to learn how to use git-pull/fetch/clone commands to automatically bring the summod repository in.
