### ISSUE TITLE
Therodian music enthusiasts plague sieged forts

### ISSUE THREAD

**Issue by Lambert-Simnel** [sum1won/summod#120]
Forts on the coast under siege by therodian forces have found therodian builders erect music arenas within the walls.

**Comment by SomeGent** [comment]
Subbed in as Ermor and noticed the issue. Province history seems to indicate that Thero never owned the territory. It's unknown whether Thero ever had candles there. A priest on preaching duty and the loss of faith event suggests that Thero may have had candles there in the past. 
![provincehistory](https://cloud.githubusercontent.com/assets/22383685/18771314/f4d92538-810b-11e6-974b-e6001fbc32cd.PNG)

![strangeness](https://cloud.githubusercontent.com/assets/22383685/18771277/a67bd534-810b-11e6-8117-322c3b33da81.PNG)

![dancer](https://cloud.githubusercontent.com/assets/22383685/18773025/3cecce3a-8119-11e6-8525-8fec35fe84b9.PNG)

**Comment by sum1won** [comment]
Huh.  This seems to result from the fact that thero is considered to "control" a province while it is sieging it.  The site should disappear if thero is remove from the siege.  I have some ideas to reduce frequency, but it can't be removed entirely.
