### ISSUE TITLE
LA Pythium solar cult bug?

### ISSUE THREAD

**Issue by scalemaildev** [sum1won/summod#138]
From /domg/:

CastinthenameofBob Pythium  11/29/16(Tue)19:35:24 No.161436645▶>>161436979
Hey Admin, can you delete Lines 11088 to 11197 (inclusive) of Summod. There's a bug that's deleting all my sacreds as soon as they're recruited, which kind of sucks.

**Comment by sum1won** [comment]
Fixed.  Will be in next version.
