### ISSUE TITLE
Reduce unnecessary events

### ISSUE THREAD

**Issue by sum1won** [sum1won/summod#15]

**Comment by sum1won** [comment]
Major event hogs:

Eater of the dead: 6 events.  Clean up code - nonevent code?

Tarrasque: Two events.
Events for each nation: 70 events?
Bribe Events: 4.  Can probably reduce (ermor/lemuria?)
Abysia: Assassin: 26 events.  Can probably be reduced to 14.
Amulet of the fish: 5 events
Marignon flaggies: 21 events (reduce complexity).  Temple bonuses, dominion bonuses
China Conscription desertion: 50 events.
Hearthiding: 55 events.
Therodos: Spawning 17 events
Therodos Recruitment: 35 events - can probably remove redundancy side-checks.
Deadland mechanics: 26 events
Knight events: 26 - can remove 13 treasure events
Unicorn, warden events: 5 (note: line 6236 needs correction, as its supposed to be the nonmagic removal, not nofort)

**Comment by Lambert-Simnel** [comment]
Lemurian Indie priests can't reanimate.

**Comment by sum1won** [comment]
Yes, that's why that's getting removed.

**Comment by Lambert-Simnel** [comment]
I'll do a proper pull request at some point, but here's how to elliminate the conscription events:

-snipped-

**Comment by sum1won** [comment]
Events reduced by 70.

**Comment by sum1won** [comment]
Major event hogs:

Events for each nation: 70 events?
Bribe Events: 3.  Can probably reduce (ermor/lemuria?)
Abysia: Assassin: 14 events.  
Amulet of the fish: 5 events
Marignon flaggies: 21 events (reduce complexity).  Temple bonuses, dominion bonuses
China Conscription desertion: 50 events.
Hearthiding: 55 events.
Therodos: Spawning 17 events
Therodos Recruitment: 29 events - can probably remove redundancy side-checks.
Deadland mechanics: 26 events
Knight events: 13
Unicorn, warden events: 5 (note: line 6236 needs correction, as its supposed to be the nonmagic removal, not nofort)

**Comment by Lambert-Simnel** [comment]
Concription is eventless now.
Having looked through hearthiding I'm impressed it only takes 55 events.

I'm not sure which of the others can be done without events, honestly.

Edit: Actually can't you drop the nationstart events and just change their description to ONLY contain a detailed bit about them in summod?

Also the event total is **233** currently.
