### ISSUE TITLE
Tlalhuepuchi somehow require water to summon now.

### ISSUE THREAD

**Issue by sum1won** [sum1won/summod#18]

**Comment by Lambert-Simnel** [comment]
You put:
#selectspell 340 --tlahuelpuchi
#path 0 7
#path 0 2
#path 1 5
#pathlevel 1 2
#end
You need to put
#selectspell 340 --tlahuelpuchi
#path 0 7
#path**level** 0 2
#path 1 5
#pathlevel 1 2
#end

**Comment by sum1won** [comment]
i smrt
