### ISSUE TITLE
Prophetshapes

### ISSUE THREAD

**Issue by Moggers** [sum1won/summod#20]
Many mages are meant to change shapes and accrue paths when they are prophetized. Lizard Shamans getting S2N2 is one example, I believe Abysia also has a mage with a prophetshape.

**Comment by sum1won** [comment]
Shamans are the only ones with enhanced magic as far as I can tell.  +1S and +2N now, which means illwinter did a stealth change again.

**Comment by Moggers** [comment]
Fuck. S2 is that actual useful part. EA Ctis already has very easy n2 access.
Damn you illwinter.

**Comment by Lambert-Simnel** [comment]
Issue: Illwinter randomly does stupid and annoying stuff.
Solution: Undo all those changes?
