### ISSUE TITLE
Blast of Unlife

### ISSUE THREAD

**Issue by Moggers** [sum1won/summod#27]
Blast of unlife rarely sees use due to a combination of MRN, low damage, difficult access, and generally just being eclipsed by shadow blast in every way.

> You could change blast of unlife to D2, increase fatigue to 30, and remove MRN. That would be a decent evocation, but the uses wouldn't overlap with shadow blast much.
> Shadow Bolt and Bolt of Unlife could probably be made D1 (MRN, single target, not great precision - compare to frozen heart or stellar cascades). D1 can't even cast shadow blast, so that wouldn't overlap either.

**Comment by sum1won** [comment]
I appreciate they are underused, but I am leery of buffing death magic.

**Comment by Moggers** [comment]
How come? Death is by no means the top dog.
It's a very skewed path with little to nothing in terms of damage potential. This is fine for nations which can get their damage potential else where. But nations with death as a major path are screwed. They have no form of evocation. At all.
