### ISSUE TITLE
Make some ND crosspaths

### ISSUE THREAD

**Issue by Moggers** [sum1won/summod#5]
Right now there's just Lamias and Manikins. Both of which are useless. Lamia Queens could be useful for breaking into blood if they had better blood rolls.
I had a look at poison golem and it seems really cool, golem makes sense as earth, but poison is thematically nature. So ND there works well if it takes death as one of the paths.

**Comment by Moggers** [comment]
#7 How about this? Earth already has heaps of useful shit and poison is thematically nature.

**Comment by sum1won** [comment]
Nature and death already have a near-monopoly on late-game SC chassis.  I'd rather not compound that.  (Also, manikins etc are improved in mod).

Other issue is I tried something similar in an early version and it met negative feedback re: "wrong sort of poison."  More like BVC type "poison" than poison per se.
