### ISSUE TITLE
Eunech conscription missing

### ISSUE THREAD

**Issue by Lambert-Simnel** [sum1won/summod#58]
It's as absent as their testicles.

**Comment by sum1won** [comment]
Should have been fixed in the pending version.  If not, I'll do it with the
next bunch this weekend

**Comment by Lambert-Simnel** [comment]
Well, good, thought you were going to say they're already fixed.

**Comment by sum1won** [comment]
Fetch me my scissors!

**Comment by Lambert-Simnel** [comment]
Scissors, MRN negates, maleonly 999+damage Raise on kill:Eunech
