### ISSUE TITLE
New Balance

### ISSUE THREAD

**Issue by sum1won** [sum1won/summod#87]
Therodos is too good now.  Sacreds repeatedly cited as the killer unit - two attacks is too many to handle.  With berserk they're just short of vanheres, allegedly.  Thinking of dropping the extra attack to be either a kick, or 50% as effective.

Other stuff also might need addressing - ghosts are superb uw expanders to the extent they can blind expand, and the new mage is bretty gud.

**Comment by Lambert-Simnel** [comment]
Ghosts were superb expanders before, this hasn't changed in Summod, not that this means it shouldn't change.

**Comment by Lambert-Simnel** [comment]
Ideas:
1. Change the one attack to being a bunch of seperate melee50 attacks. Three would be my choice, making the attack density the same as size 2 one weapon fighters, whilst making them less reliable.
2. If blind expansion turn 1 is too much of an issue, make the starting party of merman/triton mercs.
3. Teach people to actually use sleep cloud + so such, I mean come on.
4. Change recruitment to be in pairs, same way that in the Bretonnian mod you get a pegasus knight with each pegasus lord. This cuts down the flow of sacreds slightly and incentivises prod a bit more.
