### ISSUE TITLE
Scaling Quickness Doublecheck

### ISSUE THREAD

**Issue by sum1won** [sum1won/summod#96]

**Comment by Lambert-Simnel** [comment]
Apparently very strong with W9 dormant god, any other issues?

**Comment by sum1won** [comment]
That's it.  Maybe single target scaling?

**Comment by Lambert-Simnel** [comment]
Is there any way to make it scale slower, say at 1/2 rate?

**Comment by sum1won** [comment]
Not really, afaik

**Comment by Lambert-Simnel** [comment]
We could just make there be lots of different qucikness spells, all not scaling?
