### ISSUE TITLE
Ur Buffs

### ISSUE THREAD

**Issue by sum1won** [sum1won/summod#97]

**Comment by Lambert-Simnel** [comment]
Personally I like the Sirush + Lion PD to be part of it, from the Ishtar Gate, as well as the other sirrush buffs I made, mostly because I feel it makes them relevent but not the only option for Ur.

Might need other buffs as well, though.

**Comment by sum1won** [comment]
I like the lion pd especially.  I'm not sure how the sirrush pd works, but I'll take a look at your code.

My buffs are going to have two focuses:  

1.) improving the way elegists work.  I might increase the score a little, and I will also give them healer as long as they are in the capital, so they can heal the god (or whoever visits the capital).
2.) Improving mainline recruitables.  Much like muuch, a lot of the ur troops are barely distinguishable in terms of skill/cost/equipment.  Making some clearer tiers would help with that (as would a slight stats increase

I also might do some other shit,  Making berserkers recruitable in cap seems like a good idea.  Probably.

**Comment by Lambert-Simnel** [comment]
It just replaces what they usually have as fort PD, standard nation code stuff.

Is there any way to make a spell that only targets gods? Or could we just make all the chasis for Ur have recuperation?
HEAVY ARMOURED ENKIDU!

**Comment by Lambert-Simnel** [comment]
I have asked for Mith to make some hats, so at least we can differentiate by that, armour weight and weapon type.

**Comment by sum1won** [comment]
Ur changelog wasn't compatibile.  Copied pd part out for use.
